### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by prsng** [tejonrojo/homebridge-apsystem-inverter#1]
I don't see the plugin working anymore.
Does it need updates with dependencies?

**Comment by tejonrojo** [comment]
Ap systems change their api. I will try to fix it

**Comment by ghost** [comment]
Any updates on this?

**Comment by gpsgeo** [comment]
I too would like to know if there are any updates.

**Comment by iceonu2** [comment]
same here please

**Comment by chrisgagne** [comment]
Same here please, happy to send you money for a beer :)

**Comment by EddieDSuza** [comment]
seems like the API link has changed from `http://api.apsystemsema.com:8073/apsema/v1/ecu/getPowerInfo` to 
`http://api.apsystemsema.com:8073/apsema/v1/apisystem/getSystemPowerInfo`

See here that I was able to download - 
[Apsystems EMA API operation manual.pdf](https://github.com/tejonrojo/homebridge-apsystem-inverter/files/13952732/Apsystems.EMA.API.operation.manual.pdf)

So when I updated the link in `index.js` it doesnt throw any errors. the plugin loads but doesnt provide any values. Now the values report in Current Ambient Light Level aka. Lux

<img width="172" alt="Screenshot 2024-01-16 at 12 57 40" src="https://github.com/tejonrojo/homebridge-apsystem-inverter/assets/52710883/5e38f815-fec0-4557-ba28-adc6d06f8d4c">
<img width="799" alt="Screenshot 2024-01-16 at 12 57 33" src="https://github.com/tejonrojo/homebridge-apsystem-inverter/assets/52710883/a0a21096-4ff2-4d74-b1f9-770dfd36503c">

Now sure what else is needed. In Home Assistant you have to also provide the `authId` & `systemId` which I have done and works as expected.

**Comment by tejonrojo** [comment]
Hello, the problem is that the api is not free. I think that we need to change the approch to a local service like home assistant do. https://community.home-assistant.io/t/apsystem-solar-energy-integration

**Comment by EddieDSuza** [comment]
I'd be happy to help as well since I got the solution working with HA

**Comment by iceonu2** [comment]
> I'd be happy to help as well since I got the solution working with HA

👍🏻

**Comment by pzim-devdata** [comment]
Hello did you try this : https://github.com/SonnenladenGmbH/APsystems-EZ1-API

For working, you will need to activate the "Local Mode" :
Step 1: Connect to the inverter using the "Direct Connection" method. (Disconnect from your account in the app first)
Step 2: Establish a connection with your inverter.
Step 3: Select the Settings menu.
Step 4: Switch to the "Local Mode" section.
Step 5: Activate local mode and select "Continuous"
Step 6: Done! Make a note of the IP address for future reference.

Go to http://{IP address}:8050/getOutputData
http://{IP address}:8050/getDeviceInfo
http://{IP address}:8050/getAlarm
http://{IP address}:8050/getOnOff
http://{IP address}:8050/getMaxPower
To set maxpower : http://{IP address}:8050/setMaxPower?p=600 for 600W
To power off : http://{IP address}:8050/setOnOFF?status=1 1=off 0=On

If you don't find the local mode, you will need to upgrade the firmware : contact APsystems ([emea@apsystems.com](mailto:emea@apsystems.com)) and give them the serial nummer of the inverter : EXXXXXXXXXX for asking them to upgrade to version :
1.7.1 (no battery) or 2.0.1_b (with battery)

The documentation is here : https://github.com/SonnenladenGmbH/APsystems-EZ1-API/blob/main/assets/apsystems-documentation/APsystems%20EZ1%20Local%20API%20-%20Documentation.pdf
